name: CI

on:
  push:
    branches: [ main ]
jobs:
  build-image:
    name: build flask app
    runs-on: ubuntu-latest

  #branch checkout
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: configure aws creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2   #${{ secrets.name }}

      - name: login to ecr
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag and push to ecr
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.output.registry }}
          ECR_REPOSITORY: ak-hello-flask
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker images

    #   - name: test
    #     run: |
    #       aws --version
    # # steps:
    #   - name: test
    #     run: |
    #       aws --version
